# Generated by Django 5.2.11 on 2026-03-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0003_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
