# Generated by Django 5.2.11 on 2026-03-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0004_alter_session_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
