# Generated by Django 5.2.12 on 2026-03-19 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0005_alter_session_options_alter_session_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='end_time',
            field=models.TimeField(verbose_name='זמן סיום'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='goal',
            field=models.TextField(verbose_name='מטרת הלימוד'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='hourly_rate',
            field=models.IntegerField(verbose_name='תשלום לשעה'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sponsor',
            field=models.CharField(choices=[('P', 'הורים'), ('S', 'ישיבה'), ('O', 'יגדל/קופה')], default='P', max_length=1, verbose_name='מממן'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_time',
            field=models.TimeField(verbose_name='זמן התחלת הלימוד היומי'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.student', verbose_name='בחור'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='אברך'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='שם התלמיד'),
        ),
    ]
