# Generated by Django 5.2.12 on 2026-04-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0006_alter_assignment_end_time_alter_assignment_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
