# Generated by Django 5.2.12 on 2026-04-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0007_alter_session_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time_started',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
