# Generated by Django 5.2.12 on 2026-04-13 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0008_alter_session_time_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='assignment',
            name='session_length',
            field=models.TimeField(default=datetime.time(1, 0), verbose_name='אורך שיעור'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='session_rate',
            field=models.IntegerField(default=55, verbose_name='תשלום לשיעור'),
            preserve_default=False,
        ),
    ]
