# Generated by Django 5.2.12 on 2026-04-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0009_remove_assignment_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='session_length',
            field=models.DurationField(verbose_name='אורך שיעור'),
        ),
    ]
