# Generated by Django 5.2.12 on 2026-04-16 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0011_monthlyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='billing_mode',
            field=models.CharField(choices=[('session', 'לפי שיעור'), ('month', 'לפי חודש')], default='session', max_length=20, verbose_name='צורת חיוב'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='תשלום חודשי'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='sessions_per_week',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='מספר מפגשים בשבוע'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='session_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='תשלום לשיעור'),
        ),
        migrations.CreateModel(
            name='AttendanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='תאריך')),
                ('adjustment_type', models.CharField(choices=[('late', 'איחור'), ('absent', 'חיסור')], max_length=12, verbose_name='סוג')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='הערה')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoring.assignment')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
