# Generated by Django 5.2.12 on 2026-04-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0012_assignment_billing_mode_assignment_monthly_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceadjustment',
            name='note',
        ),
        migrations.AddField(
            model_name='attendanceadjustment',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='משך האיחור'),
        ),
    ]
