# Generated by Django 5.2.12 on 2026-04-17 11:02

from django.db import migrations, models


def copy_legacy_student_names(apps, schema_editor):
    Student = apps.get_model("tutoring", "Student")
    for student in Student.objects.filter(last_name="", name__gt=""):
        student.last_name = student.name
        student.save(update_fields=["last_name"])


def restore_legacy_student_names(apps, schema_editor):
    Student = apps.get_model("tutoring", "Student")
    for student in Student.objects.filter(name="", last_name__gt=""):
        student.name = student.last_name
        student.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring', '0013_remove_attendanceadjustment_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='שם פרטי'),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='שם משפחה'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='שם התלמיד'),
        ),
        migrations.RunPython(copy_legacy_student_names, restore_legacy_student_names),
    ]
